# Server
server.port=8080

# MongoDB Atlas (NEW PROPERTY)
spring.mongodb.uri=mongodb+srv://dinesh:dinesh123@hospital-cluster.qr9qkqy.mongodb.net/hospital_db?retryWrites=true&w=majority

# Thymeleaf
spring.thymeleaf.cache=false
